Implement architecture separation
Fixes # 129.
Fixes # 248.

Tooling changes (more details in the updated docs/package.md):

* Added the `archs` field for declaring which device(s) a recipe is
  compatible with. Supported values are `rmall` (for device-independent
  packages), `rm1` (for reMarkable 1) and `rm2` (for reMarkable 2).
  When multiple arch values are set for a recipe, the recipe is
  generated once per entry, which allows specializing builds for
  specific devices.
* Replaced the `depends` field with an `installdepends` field used for
  declaring install-time dependencies. Previously, dependencies declared
  in the `depends` field were fulfilled both at build time and at
  install time, with no way of declaring install-time-only dependencies.
* Changed the web package listing to include download links for each
  available architecture of each package.
* Packages are now stored in subdirectories named after their
  architecture. This is because opkg does not like seeing packages for
  architectures other than the ones it is configured to accept in
  opkg.conf. With this layout change, we can make opkg happy by
  directing it to only the subdirectories containing packages for
  enabled architectures.

Install changes:

* The bootstrap script now adds the `rmall` architecture on all
  installs, and the `rm1` or `rm2` architecture depending on the type of
  the device it’s executed on. It will fail if the device is not of a
  recognized type (based on the value of `/sys/devices/soc0/machine`).
  It also selects the repositories appropriate for the current
  architecture.

rm2fb changes:

* The package was split into two packages, `display` (which provides the
  rm2fb server on rM2 and is an empty package on rM1) and `rm2fb-shim`
  (which provides the client shim on rM2 and a mock shim on rM1).
* The `rm2fb-server` command was removed (the most common use-case being
  that the display server is started from the systemd unit).
* The `rm2fb-client` command was renamed to `rm2fb-shim`, with the
  expectation that users will not need it anymore, unless for
  development purposes.

Apps marked as reMarkable-1-only:

* appmarkable (https://github.com/LinusCDE/ - appmarkable/issues/2)
* rmservewacominput (because it depends on appmarkable)
* vnsee (https://github.com/matteodelabre/ - vnsee/issues/15)
* whiteboard-hypercard (https://github.com/fenollp/ - reMarkable-tools/issues/12)

Apps marked as reMarkable-2-only:

* rm2-suspend-fix

Apps updated to include the rM2 shim:

* calculator
* chessmarkable
* draft
* fingerterm
* keywriter
* koreader (through setting LD_PRELOAD in the existing wrapper script)
* oxide
* plato
* recrossable
* remarkable-splash
* retris
* rmkit
* xochitl (through a new wrapper script at /opt/bin/xochitl)
* zshelf

diff --git a/package/rm2fb/package b/package/rm2fb/package
--- a/package/rm2fb/package
+++ b/package/rm2fb/package
@@ -1,67 +1,103 @@
 #!/usr/bin/env bash
-# Copyright (c) 2020 The Toltec Contributors
+# Copyright (c) 2021 The Toltec Contributors
 # SPDX-License-Identifier: MIT
 
-pkgnames=(rm2fb)
+archs=(rm1 rm2)
+pkgnames=(display rm2fb-shim)
 timestamp=2021-02-21T01:41+00:00
 maintainer="raisjn <of.raisjn@gmail.com>"
 license=MIT
-pkgdesc="Interface to the reMarkable 2 framebuffer"
 url="https://github.com/ddvk/remarkable2-framebuffer"
-pkgver=1.0.0-8
+pkgver=1.0.0-9
 section="devel"
 
-image=qt:v1.1
+image=qt:v1.4
 source=(
     https://github.com/ddvk/remarkable2-framebuffer/archive/0724acfcc87c24ae2fcb45db4cad033981f3f4a9.zip
-    rm2fb.conf
     rm2fb.service
-    rm2fb-server
-    rm2fb-client
+    rm2fb-shim
 )
 sha256sums=(
     bf398905f43e189671692325444e0cac131ab9856f215adabe6b8747aaa41351
     SKIP
     SKIP
-    SKIP
-    SKIP
 )
 
 build() {
-    qmake
-    make
-}
-
-package() {
-    mkdir -p "$pkgdir"/opt/lib "$pkgdir"/opt/etc "$pkgdir"/opt/bin
-    install -D -m 755 "$srcdir"/src/client/librm2fb_client.so.${pkgver%-*} "$pkgdir"/opt/lib/
-    install -D -m 755 "$srcdir"/src/server/librm2fb_server.so.${pkgver%-*} "$pkgdir"/opt/lib/
-    install -D -m 755 "$srcdir"/rm2fb-server "$pkgdir"/opt/bin/
-    install -D -m 755 "$srcdir"/rm2fb-client "$pkgdir"/opt/bin/
-    install -D -m 644 "$srcdir"/rm2fb.conf "$pkgdir"/etc/systemd/system.conf.d/01-rm2fb.conf
-    install -D -m 644 "$srcdir"/rm2fb.service "$pkgdir"/lib/systemd/system/rm2fb.service
-}
-
-configure() {
-    systemctl daemon-reload
-    systemctl enable rm2fb --now
-    # Restart xochitl if it's running
-    if systemctl --quiet is-active xochitl; then
-        # Reset the crash count so we don't trigger remarkable-fail
-        echo "0" > /tmp/crashnum
-        systemctl restart xochitl
+    if [[ $arch = rm1 ]]; then
+        # Create an empty client library for rM1
+        pushd src/client
+        echo | "${CROSS_COMPILE}gcc" \
+            -fPIC -fvisibility=hidden -shared \
+            -o librm2fb_client.so.${pkgver%-*} \
+            -xc -
+        popd
+    else
+        qmake
+        make
     fi
 }
 
-preremove() {
-    if systemctl list-units --full -all | grep -Fq 'rm2fb.service'; then
-        systemctl disable rm2fb --now
-    fi
-    echo -n "make sure "
-    if ! is-enabled xochitl.service; then
-        echo "to re-enable xochitl with 'systemctl enable xochitl --now'"
-        echo -n "and "
-    fi
-    echo "to disable / uninstall any launchers like draft, oxide or remux before"
-    echo "rebooting your tablet to complete the uninstallation"
+display() {
+    pkgdesc="Interface to the reMarkable framebuffer"
+
+    package() {
+        if [[ $arch = rm2 ]]; then
+            libname="librm2fb_server.so.${pkgver%-*}"
+            install -D -m 644 -t "$pkgdir"/opt/lib "$srcdir"/src/server/"$libname"
+            ln -s "$libname" "$pkgdir"/opt/lib/"${libname%.*}"
+            ln -s "${libname%.*}" "$pkgdir"/opt/lib/"${libname%.*.*}"
+            ln -s "${libname%.*.*}" "$pkgdir"/opt/lib/"${libname%.*.*.*}"
+            install -D -m 644 -t "$pkgdir"/lib/systemd/system \
+                "$srcdir"/rm2fb.service
+        fi
+    }
+
+    configure() {
+        if [[ $arch = rm2 ]]; then
+            systemctl daemon-reload
+            systemctl enable rm2fb --now
+            # Restart xochitl if it's running
+            if systemctl --quiet is-active xochitl; then
+                # Reset the crash count so we don't trigger remarkable-fail
+                echo "0" > /tmp/crashnum
+                systemctl restart xochitl
+            fi
+        fi
+    }
+
+    preremove() {
+        if [[ $arch = rm2 ]]; then
+            if systemctl list-units --full -all | grep -Fq 'rm2fb.service'; then
+                systemctl disable rm2fb --now
+            fi
+            echo -n "make sure "
+            if ! is-enabled xochitl.service; then
+                echo "to re-enable xochitl with 'systemctl enable xochitl --now'"
+                echo -n "and "
+            fi
+            echo "to disable / uninstall any launchers like draft, oxide or remux before"
+            echo "rebooting your tablet to complete the uninstallation"
+        fi
+    }
+}
+
+rm2fb-shim() {
+    pkgdesc="Shim to make reMarkable 1 apps work on reMarkable 2"
+    installdepends=(display)
+
+    package() {
+        libname="librm2fb_client.so.${pkgver%-*}"
+        install -D -m 644 -t "$pkgdir"/opt/lib "$srcdir"/src/client/"$libname"
+        install -d "$pkgdir"/usr/lib
+        ln -s /opt/lib/"$libname" "$pkgdir"/usr/lib/"$libname"
+
+        for dest in opt/lib usr/lib; do
+            ln -s "$libname" "$pkgdir/$dest/${libname%.*}"
+            ln -s "${libname%.*}" "$pkgdir/$dest/${libname%.*.*}"
+            ln -s "${libname%.*.*}" "$pkgdir/$dest/${libname%.*.*.*}"
+        done
+
+        install -D -m 755 -t "$pkgdir"/opt/bin "$srcdir"/rm2fb-shim
+    }
 }
